/*
 * Copyright 2014 mango.jfaster.org
 *
 * The Mango Project licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

package org.jfaster.mango.crud;

import org.jfaster.mango.annotation.*;
import org.jfaster.mango.util.Strings;
import org.jfaster.mango.util.bean.BeanUtil;
import org.jfaster.mango.util.bean.PropertyMeta;

import javax.annotation.Nullable;
import java.lang.reflect.Type;
import java.util.*;

/**
 * @author ash
 */
public class CrudMeta {

  private final List<String> properties;

  private final List<String> columns;

  private final Map<String, String> propertyToColumnMap;

  private final Map<String, Type> propertyToTypeMap;

  // 使用 @ID 修饰的类属性
  private final String property4Id;

  // 使用 @ID 修饰的类属性对应的数据库列
  private final String column4Id;

  // 使用 @AutoGenerated 修饰的类属性
  private final String property4AutoGenerated;

  // 使用 @AutoGenerated 修饰的类属性对应的数据库列
  private final String column4AutoGenerated;

  public CrudMeta(Class<?> clazz) {
    List<String> props = new ArrayList<String>();
    List<String> cols = new ArrayList<String>();
    Map<String, String> propToColMap = new HashMap<String, String>();
    HashMap<String, Type> propToTypeMap = new HashMap<String, Type>();
    String prop4Id = null;
    String col4Id = null;
    String prop4AutoGenerated = null;
    String col4AutoGenerated = null;

    for (PropertyMeta propertyMeta : BeanUtil.fetchPropertyMetas(clazz)) {
      if (isIgnoredProperty(propertyMeta)) {
        continue;
      }

      String prop = propertyMeta.getName();
      String col = extractColumnName(propertyMeta);

      props.add(prop);
      cols.add(col);
      propToColMap.put(prop, col);
      propToTypeMap.put(prop, propertyMeta.getType());

      prop4Id = extractIdProperty(propertyMeta, prop4Id, col4Id, prop, col);
      prop4AutoGenerated = extractAutoGeneratedProperty(propertyMeta, prop4AutoGenerated, col4AutoGenerated, prop, col);
    }

    properties = Collections.unmodifiableList(props);
    columns = Collections.unmodifiableList(cols);
    propertyToColumnMap = Collections.unmodifiableMap(propToColMap);
    propertyToTypeMap = Collections.unmodifiableMap(propToTypeMap);
    this.property4Id = prop4Id;
    this.column4Id = col4Id;
    this.property4AutoGenerated = prop4AutoGenerated;
    this.column4AutoGenerated = col4AutoGenerated;
  }

  private boolean isIgnoredProperty(PropertyMeta propertyMeta) {
    return propertyMeta.getPropertyAnno(Ignore.class) != null;
  }

  private String extractColumnName(PropertyMeta propertyMeta) {
    Column colAnno = propertyMeta.getPropertyAnno(Column.class);
    return colAnno != null ?
        colAnno.value() :
        Strings.underscoreName(propertyMeta.getName());
  }

  private String extractIdProperty(PropertyMeta propertyMeta, String prop4Id, String col4Id, String prop, String col) {
    if (propertyMeta.getPropertyAnno(ID.class) != null || propertyMeta.getPropertyAnno(AutoGeneratedID.class) != null) {
      if (prop4Id != null || col4Id != null) {
        throw new IllegalStateException("duplicate @ID annotation");
      }
      return prop;
    }
    return prop4Id;
  }

  private String extractAutoGeneratedProperty(PropertyMeta propertyMeta, String prop4AutoGenerated, String col4AutoGenerated, String prop, String col) {
    if (propertyMeta.getPropertyAnno(AutoGenerated.class) != null || propertyMeta.getPropertyAnno(AutoGeneratedID.class) != null) {
      if (prop4AutoGenerated != null || col4AutoGenerated != null) {
        throw new IllegalStateException("duplicate @AutoGenerated annotation");
      }
      return prop;
    }
    return prop4AutoGenerated;
  }

//Refactoring end

  public List<String> getProperties() {
    return properties;
  }

  public List<String> getColumns() {
    return columns;
  }

  @Nullable
  public String getColumnByProperty(String property) {
    return propertyToColumnMap.get(property);
  }

  @Nullable
  public Type getTypeByProperty(String property) {
    return propertyToTypeMap.get(property);
  }

  public String getProperty4Id() {
    return property4Id;
  }

  public String getColumn4Id() {
    return column4Id;
  }

  public String getProperty4AutoGenerated() {
    return property4AutoGenerated;
  }

  public String getColumn4AutoGenerated() {
    return column4AutoGenerated;
  }

}
